# Generated by Django 3.2.4 on 2021-06-05 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='title_color',
            field=models.IntegerField(choices=[(0, 'white'), (1, 'black')], default=0),
        ),
    ]
